# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'text_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 672)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, -30, 811, 711))
        self.tabWidget.setStyleSheet("background-color: rgb(242, 255, 225);")
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.scrol_input = QtWidgets.QScrollArea(self.tab)
        self.scrol_input.setGeometry(QtCore.QRect(60, 130, 671, 221))
        self.scrol_input.setStyleSheet("QScrollBar:vertical {\n"
"    background-color: rgb(197, 197, 197);\n"
"    border: none;    \n"
"    width: 15px;               \n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical{\n"
"    border: None;    \n"
"    background-color: rgb(134, 134, 134);\n"
"}\n"
"QScrollBar:up-arrow:vertical, QScrollBar:down-arrow:vertical{\n"
"    background: None;\n"
"}\n"
"QScrollBar:add-page:vertical, QScrollBar:sub-page:vertical{\n"
"    background: None;\n"
"}\n"
"\n"
"\n"
"                           \n"
"")
        self.scrol_input.setWidgetResizable(True)
        self.scrol_input.setObjectName("scrol_input")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 669, 219))
        self.scrollAreaWidgetContents_4.setStyleSheet("")
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.text_input = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_4)
        self.text_input.setGeometry(QtCore.QRect(0, -4, 671, 221))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_input.setFont(font)
        self.text_input.setStyleSheet("border: None;\n"
"background-color: rgb(244, 244, 244);")
        self.text_input.setObjectName("text_input")
        self.scrol_input.setWidget(self.scrollAreaWidgetContents_4)
        self.label_input = QtWidgets.QLabel(self.tab)
        self.label_input.setGeometry(QtCore.QRect(70, 40, 641, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_input.setFont(font)
        self.label_input.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input.setObjectName("label_input")
        self.btn_save = QtWidgets.QPushButton(self.tab)
        self.btn_save.setGeometry(QtCore.QRect(300, 377, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_save.setFont(font)
        self.btn_save.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.btn_save.setObjectName("btn_save")
        self.btn_view = QtWidgets.QPushButton(self.tab)
        self.btn_view.setGeometry(QtCore.QRect(300, 470, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_view.setFont(font)
        self.btn_view.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.btn_view.setObjectName("btn_view")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setEnabled(True)
        self.tab_2.setObjectName("tab_2")
        self.title_text = QtWidgets.QLabel(self.tab_2)
        self.title_text.setGeometry(QtCore.QRect(25, 39, 721, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.title_text.setFont(font)
        self.title_text.setAlignment(QtCore.Qt.AlignCenter)
        self.title_text.setObjectName("title_text")
        self.btn_back = QtWidgets.QPushButton(self.tab_2)
        self.btn_back.setGeometry(QtCore.QRect(20, 540, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.btn_back.setObjectName("btn_back")
        self.scroll_text = QtWidgets.QScrollArea(self.tab_2)
        self.scroll_text.setEnabled(True)
        self.scroll_text.setGeometry(QtCore.QRect(20, 120, 761, 391))
        font = QtGui.QFont()
        font.setKerning(True)
        self.scroll_text.setFont(font)
        self.scroll_text.setStyleSheet("\n"
"QScrollBar:vertical {    \n"
"    background-color: rgb(197, 197, 197);\n"
"    border: none;    \n"
"    width: 15px;               \n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical{\n"
"    border: None;    \n"
"    background-color: rgb(134, 134, 134);\n"
"}\n"
"QScrollBar:up-arrow:vertical, QScrollBar:down-arrow:vertical{\n"
"    background: None;\n"
"}\n"
"QScrollBar:add-page:vertical, QScrollBar:sub-page:vertical{\n"
"    background: None;\n"
"}\n"
"\n"
"\n"
"                           \n"
"")
        self.scroll_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scroll_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scroll_text.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scroll_text.setWidgetResizable(True)
        self.scroll_text.setAlignment(QtCore.Qt.AlignCenter)
        self.scroll_text.setObjectName("scroll_text")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setEnabled(True)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 759, 389))
        self.scrollAreaWidgetContents_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.text_label_ = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.text_label_.setEnabled(True)
        self.text_label_.setMinimumSize(QtCore.QSize(0, 0))
        self.text_label_.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_label_.setFont(font)
        self.text_label_.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.text_label_.setStyleSheet("border: None;\n"
"background-color: rgb(244, 244, 244);")
        self.text_label_.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_label_.setText("")
        self.text_label_.setTextFormat(QtCore.Qt.AutoText)
        self.text_label_.setScaledContents(True)
        self.text_label_.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.text_label_.setWordWrap(True)
        self.text_label_.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.text_label_.setObjectName("text_label_")
        self.verticalLayout_2.addWidget(self.text_label_)
        self.scroll_text.setWidget(self.scrollAreaWidgetContents_2)
        self.redact_btn = QtWidgets.QPushButton(self.tab_2)
        self.redact_btn.setGeometry(QtCore.QRect(660, 540, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.redact_btn.setFont(font)
        self.redact_btn.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.redact_btn.setObjectName("redact_btn")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.scroll_change = QtWidgets.QScrollArea(self.tab_3)
        self.scroll_change.setGeometry(QtCore.QRect(20, 150, 741, 311))
        self.scroll_change.setMinimumSize(QtCore.QSize(200, 200))
        self.scroll_change.setStyleSheet("QScrollBar:vertical {\n"
"    background-color: rgb(197, 197, 197);\n"
"    border: none;    \n"
"    width: 15px;               \n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical{\n"
"    border: None;    \n"
"    background-color: rgb(134, 134, 134);\n"
"}\n"
"QScrollBar:up-arrow:vertical, QScrollBar:down-arrow:vertical{\n"
"    background: None;\n"
"}\n"
"QScrollBar:add-page:vertical, QScrollBar:sub-page:vertical{\n"
"    background: None;\n"
"}\n"
"\n"
"\n"
"                           \n"
"")
        self.scroll_change.setWidgetResizable(True)
        self.scroll_change.setObjectName("scroll_change")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 739, 309))
        self.scrollAreaWidgetContents.setAutoFillBackground(False)
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.save_input = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.save_input.setGeometry(QtCore.QRect(1, 1, 741, 311))
        self.save_input.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_input.setFont(font)
        self.save_input.setStyleSheet("border: None;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.save_input.setFrameShadow(QtWidgets.QFrame.Plain)
        self.save_input.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.save_input.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.save_input.setTabChangesFocus(False)
        self.save_input.setOverwriteMode(True)
        self.save_input.setTabStopDistance(81.0)
        self.save_input.setCenterOnScroll(False)
        self.save_input.setObjectName("save_input")
        self.scroll_change.setWidget(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(20, 60, 741, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.btn_back_change = QtWidgets.QPushButton(self.tab_3)
        self.btn_back_change.setGeometry(QtCore.QRect(60, 547, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_back_change.setFont(font)
        self.btn_back_change.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.btn_back_change.setObjectName("btn_back_change")
        self.btn_change = QtWidgets.QPushButton(self.tab_3)
        self.btn_change.setGeometry(QtCore.QRect(610, 550, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_change.setFont(font)
        self.btn_change.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.btn_change.setObjectName("btn_change")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_input.setText(_translate("MainWindow", "Запишите сюда какую-ниюудь умную мысль"))
        self.btn_save.setText(_translate("MainWindow", "Save"))
        self.btn_view.setText(_translate("MainWindow", "view"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.title_text.setText(_translate("MainWindow", "Ваши записки"))
        self.btn_back.setText(_translate("MainWindow", "Back"))
        self.redact_btn.setText(_translate("MainWindow", "Redact"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.label.setText(_translate("MainWindow", "Измените запись и нажмите сохранить"))
        self.btn_back_change.setText(_translate("MainWindow", "Back"))
        self.btn_change.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
